### ISSUE TITLE
Mixin load fail on startup

### ISSUE THREAD

**Issue by elifoster** [Faboslav/variants-and-ventures#2]
### Minecraft version information

1.20.2

### Mod loader information

NeoForge

### Mod loader version information

20.2.86

### Mod version information

1.0.1

### Reproduction Steps

Install mod. Press play.

### Crash Report and latest.log

```
[20:32:04] [pool-6-thread-1/FATAL] [mixin/]: Mixin apply failed forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor -> net.minecraft.world.level.block.entity.BlockEntityType: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching f_58915_:Ljava/util/Set; in net/minecraft/world/level/block/entity/BlockEntityType for forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor->@Accessor[FIELD_GETTER]::getBlocks()Ljava/util/Set; [INJECT Applicator Phase -> forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor -> Apply Accessors ->  -> Locate -> forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor->@Accessor[FIELD_GETTER]::getBlocks()Ljava/util/Set;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching f_58915_:Ljava/util/Set; in net/minecraft/world/level/block/entity/BlockEntityType for forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor->@Accessor[FIELD_GETTER]::getBlocks()Ljava/util/Set; [INJECT Applicator Phase -> forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor -> Apply Accessors ->  -> Locate -> forge-variantsandventures-common.mixins.json:BlockEntityTypeAccessor->@Accessor[FIELD_GETTER]::getBlocks()Ljava/util/Set;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191) ~[securejarhandler-2.1.24.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:129) ~[client-1.20.2-20231019.002635-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:44) ~[client-1.20.2-20231019.002635-srg.jar%23213!/:?] {re:classloading}
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:156) ~[client-1.20.2-20231019.002635-srg.jar%23213!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?] {}
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

### Additional information

Mods installed:
```
VeganOption-mc1.20.2-0.4.0.8dccf.jar
accelerated-decay-neoforge-82.0.0.jar
AmbientEnvironment-neoforge-1.20.2-12.0.0.4.jar
appleskin-neoforge-mc1.20.2-2.5.1.jar
architectury-10.0.17-neoforge.jar
balm-neoforge-1.20.2-8.0.4.jar
cloth-config-12.0.113-neoforge.jar
collective-1.20.2-7.22.jar
cookingforblockheads-neoforge-1.20.2-17.0.1.jar
DistractingTrims-NeoForge-1.20.2-3.0.2.jar
doubledoors-1.20.2-5.2.jar
gravestone-neoforge-1.20.2-1.0.10.jar
grindstonesharpertools-1.20.2-3.4.jar
RoughlyEnoughItems-13.0.685-neoforge.jar
santastoys-630c25e.jar
tofucraft-1.20.2-7.3.0.3.jar
toms_storage-1.20.2-1.6.9.jar
ToolUpgrades-1.20.x-(v.3.2.1).jar
twilightforest-1.20.2-4.4.1977-universal.jar
```

**Comment by Faboslav** [comment]
Hello there, I tried NeoForge 20.2.86 on mc 1.20.2, basically following setup:
![Screenshot 2024-03-14 at 7 59 21](https://github.com/Faboslav/variants-and-ventures/assets/14179066/9c0d0276-43b1-496f-a071-dc98512e8a41)

It loads as expected, i am not sure what can i do about this :/.

**Comment by Faboslav** [comment]
Any updates on the issue?

**Comment by Faboslav** [comment]
Closing this, plese do open this if you have any new info or problems.

**Comment by elifoster** [comment]
I'm able to launch on 1.20.4. Not sure why it was not working for 1.20.2. Oh well.

**Comment by Faboslav** [comment]
Nevermind then, i am glad that it works at least on 1.20.4 :).
