### ISSUE TITLE
Just got a recent crash from Murk 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Faboslav/variants-and-ventures#22]
### Minecraft version information

1.21

### Mod loader information

Fabric

### Mod loader version information

0.16.0

### Mod version information

1.0.4

### Reproduction Steps

Murk firing an arrow causes ticking entity.

### Crash Report and latest.log

Crash: https://mclo.gs/FpoQ9TD
Latest Log: https://mclo.gs/Xwmh57g

**Comment by Faboslav** [comment]
Its actually probably caused by progressive archery

**Comment by makumaku1974** [comment]
> Its actually probably caused by progressive archery

I see, still buggy then.

**Comment by makumaku1974** [comment]
> Its actually probably caused by progressive archery

will forward this issue to him now.

**Comment by TenKotowsky** [comment]
Hi there, I don't have the progressive archery mod installed and I still experienced this issue.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-07-20 19:48:40
Description: Ticking entity

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at net.minecraft.class_1844.handler$bpo000$dehydration$getColorMixin(class_1844.java:527)
	at net.minecraft.class_1844.method_8064(class_1844.java)
	at net.minecraft.class_1667.method_7462(class_1667.java:59)
	at net.minecraft.class_1667.method_57316(class_1667.java:48)
	at net.minecraft.class_1667.method_7463(class_1667.java:63)
	at com.faboslav.variantsandventures.common.entity.mob.VerdantEntity.method_6996(VerdantEntity.java:61)
	at net.minecraft.class_1547.method_7105(class_1547.java:204)
	at net.minecraft.class_1380.method_6268(class_1380.java:137)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:112)
	at net.minecraft.class_1355.method_6275(class_1355.java:103)
	at net.minecraft.class_1308.method_6023(class_1308.java:794)
	at net.minecraft.class_1309.method_6007(class_1309.java:2778)
	at net.minecraft.class_1308.method_6007(class_1308.java:7200)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1547.method_6007(class_1547.java:125)
	at net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at net.minecraft.class_1308.method_5773(class_1308.java:372)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$255(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$gfb000$puzzleslib$tickNonPassenger(class_3218.java:17297)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Optional.get(Optional.java:143)
	at net.minecraft.class_1844.handler$bpo000$dehydration$getColorMixin(class_1844.java:527)
	at net.minecraft.class_1844.method_8064(class_1844.java)
	at net.minecraft.class_1667.method_7462(class_1667.java:59)
	at net.minecraft.class_1667.method_57316(class_1667.java:48)
	at net.minecraft.class_1667.method_7463(class_1667.java:63)
	at com.faboslav.variantsandventures.common.entity.mob.VerdantEntity.method_6996(VerdantEntity.java:61)
	at net.minecraft.class_1547.method_7105(class_1547.java:204)
	at net.minecraft.class_1380.method_6268(class_1380.java:137)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:112)
	at net.minecraft.class_1355.method_6275(class_1355.java:103)
	at net.minecraft.class_1308.method_6023(class_1308.java:794)
	at net.minecraft.class_1309.method_6007(class_1309.java:2778)
	at net.minecraft.class_1308.method_6007(class_1308.java:7200)
	at net.minecraft.class_1588.method_6007(class_1588.java:44)
	at net.minecraft.class_1547.method_6007(class_1547.java:125)
	at net.minecraft.class_1309.method_5773(class_1309.java:2507)
	at net.minecraft.class_1308.method_5773(class_1308.java:372)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$255(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$gfb000$puzzleslib$tickNonPassenger(class_3218.java:17297)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: variantsandventures:verdant (com.faboslav.variantsandventures.common.entity.mob.VerdantEntity)
	Entity ID: 3358
	Entity Name: Verdant
	Entity's Exact location: -211.96, 67.00, -188.46
	Entity's Block location: World: (-212,67,-189), Section: (at 12,3,3 in -14,4,-12; chunk contains blocks -224,-64,-192 to -209,319,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: -0.01, -0.08, -0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Teny_guy'/73, l='ServerLevel[New World]', x=-215.52, y=67.00, z=-197.15]]
	Chunk stats: 2601
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,63,-176), Section: (at 0,15,0 in -16,3,-11; chunk contains blocks -256,-64,-176 to -241,319,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 4950 game time, 13303 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 11325 (now: false), thunder time: 32246 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 274
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1623232208 bytes (1548 MiB) / 3468689408 bytes (3308 MiB) up to 7650410496 bytes (7296 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 26464.25
	Virtual memory used (MiB): 21195.04
	Swap memory total (MiB): 10240.00
	Swap memory used (MiB): 355.63
	Space in storage for jna.tmpdir (MiB): available: 80018.14, total: 658229.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 80018.14, total: 658229.00
	Space in storage for io.netty.native.workdir (MiB): available: 80018.14, total: 658229.00
	Space in storage for java.io.tmpdir (MiB): available: 80018.14, total: 658229.00
	Space in storage for workdir (MiB): available: 80018.14, total: 658229.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7296m -Xms256m
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.20+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		additionalstructures: Additional Structures 5.0.0-fabric
		additionz: AdditionZ 1.3.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.8.1
		advancedcombat: Advanced Combat (Revitalized) 1.21-4.3FC
		advancednetherite: Advanced Netherite 2.1.6-1.21
		ambientenvironment: AmbientEnvironment 17.0.0.5
		ambientsounds: AmbientSounds 6.0.4
		amethystequipment: Amethyst Equipment 1.0.4
		amplified_nether: Amplified Nether 1.2.5
		animal_feeding_trough: Animal Feeding Trough 1.1.1+1.21
		animatica: Animatica 0.6.1+1.21
		appleskin: AppleSkin 3.0.2+mc1.21
		architectury: Architectury 13.0.4
		armoroftheages: Armor of the Ages 1.4.1
		backslot: BackSlot 1.2.15
			amecsapi: Amecs API 1.5.5+mc1.20.2
		backslotaddon: BackSlot Addon 1.1.1
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		bclib: BCLib 21.0.8
		betterend: Better End 21.0.4
		betterf3: BetterF3 11.0.1
		betternether: Better Nether 21.0.7
		betterstats: Better Statistics Screen 3.12.4+fabric-1.21
		bobby: Bobby 5.2.3+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		boneequipment: Bone Equipment 1.0.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.0-1.21
			multipart_entities: MultipartEntities 1.7-1.21
		cardinal-components: Cardinal Components API 6.1.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			cardinal-components-item: Cardinal Components API (items) 6.1.0
			cardinal-components-level: Cardinal Components API (world saves) 6.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.0
			cardinal-components-world: Cardinal Components API (worlds) 6.1.0
		catalogue: Catalogue 1.10.1
		cinderscapes: Cinderscapes 5.0.1
			biolith: Biolith 3.0.0-alpha.1
			cinderscapes-client: Cinderscapes: Client 5.0.1
			cinderscapes-common: Cinderscapes: Common 5.0.1
			cinderscapes-worldgen: Cinderscapes: World Generation 5.0.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 11.0.0-alpha.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 11.0.0-alpha.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 11.0.0-alpha.1
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.1
		collective: Collective 7.71
		continuity: Continuity 3.0.0-beta.5+1.21
		controlify: Controlify 2.0.0-beta.14+1.21-fabric
			dev_isxander_libsdl4j: libsdl4j 3.6896c4c-38
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		controlling: Controlling 18.0.1
		creativecore: CreativeCore 2.12.4
			net_neoforged_bus: bus 7.2.0
		creeperoverhaul: Creeper Overhaul 4.0.4
		cristellib: Cristel Lib 1.2.6
			blue_endless_jankson: jankson 1.2.3
		cropsloverain: Crops Love Rain 2.1.1
		croptopia: Croptopia 3.0.4
		cyclepaintings: Cycle Paintings 3.5
		dehydration: Dehydration 1.3.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 6.0
		dragonloot: DragonLoot 1.1.5
		drippyloadingscreen: Drippy Loading Screen 3.0.7
		duckling: Duckling 5.0.1
		dynamiccrosshair: Dynamic Crosshair 8.0.3+1.21
			dynamiccrosshair-api: DynamicCrosshair API 1.0
			libbamboo: libbamboo 1.21.0.1
		easyanvils: Easy Anvils 21.0.2
		easymagic: Easy Magic 21.0.1
		elytratrims: Elytra Trims 3.4.3
			conditional-mixin: conditional mixin 0.6.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		elytratrims_extensions: Elytra Trims Extensions 2.2.1
		enchantment_lore: Enchantment Lore 1.4.0
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		enhancedvisuals: EnhancedVisuals 1.8.4
		entity-view-distance: Entity View Distance 1.3.0+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		epherolib: EpheroLib 1.2.0-1.20.6
		extractpoison: Extract Poison 3.3
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fallingleaves: Falling Leaves 1.16.1
		fancymenu: FancyMenu 3.2.5
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.3
		fleshz: FleshZ 1.5.1
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 2.0.2
		forgeconfigapiport: Forge Config API Port 21.0.5
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fpsreducer: FPS Reducer 1.21-2.9
		friendsandfoes: Friends&Foes 2.0.15
		geckoanimfix: GeckoLibIrisCompat 1.0.0
		geckolib: GeckoLib 4 4.5.7
		geophilic: Geophilic 2.4.3
		giantspawn: Giant Spawn 5.1
		glitchcore: GlitchCore 2.0.0.2
			net_jodah_typetools: typetools 0.6.3
		globalpacks: Global Data- & Resourcepacks 21.0.0
		glowing-torchflower: Glowing Torchflower 1.1.0
		gobber2: Gobber2 2.10.20
			pugh_tools: Pugh Tools 1.8.14
		grabbymobs: Grabby Mobs 1.5
		greater_eye: Greater Eye of Ender 1.7.5
		guardvillagers: GuardVillagers 2.1.2-1.21
		healingcampfire: Healing Campfire 6.0
		healthindicatortxf: Health Indicator TXF 1.21-1.2.4-fabric
			configlibtxf: ConfigLib TXF 7.2.1-fabric
		herdspanic: Herds Panic 1.1.1
		horseinboat: HorseInBoat 1.1.6
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.21
		inventoryhud: Inventory HUD + ${version}
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		jamlib: JamLib 1.0.9+1.21
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.5.0.44
		keepmysoiltilled: Keep My Soil Tilled 2.3
		konkrete: Konkrete 1.9.9
		languagereload: Language Reload 1.6.1+1.21
		libertyvillagers: Liberty's Villagers 1.0.15+fabric+1.21
		lithium: Lithium 0.12.7
		mavapi: More Axolotl Variants API 1.2.1
		mavm: More Axolotl Variants Mod 1.3.0
		melody: Melody 1.0.10
		menulogue: Menulogue 1.21-1.0.6
		midnightlib: MidnightLib 1.5.7
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.18.8+mc1.21
		monolib: MonoLib 1.3.0
		mooshroomspawn: Mooshroom Spawn 3.5
		mooshroomtweaks: Mooshroom Tweaks 3.4
		more_beautiful_torches: More Beautiful Torches 3.0.0
		more_bows_and_arrows: More Bows and Arrows 3.0.1
		mousetweaks: Mouse Tweaks 2.26
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.7-1.21
		notenoughanimations: NotEnoughAnimations 1.7.4
		obsidianui: ObsidianUI 0.2.7+mc1.21
		particlemoths: Particle Moths 2.1.0
		placeableblazerods: Placeable Blaze Rods 3.5
		placeholder-api: Placeholder API 2.4.1+1.21
		polymorph: Polymorph 1.0.4+1.21
		puffish_attributes: Pufferfish's Attributes 0.5.0
		puffish_skills: Pufferfish's Skills 0.13.1
		puzzleslib: Puzzles Lib 21.0.17
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		repurposed_structures: Repurposed Structures 7.5.3+1.21-fabric
		resourcefulconfig: Resourcefulconfig 3.0.3
		resourcefullib: Resourceful Lib 3.0.9
			com_teamresourceful_bytecodecs: bytecodecs 1.1.2
			com_teamresourceful_yabn: yabn 1.0.3
		revamped_phantoms: Revamped Phantoms 1.1.1
			dev_lukebemish_codecextras: CodecExtras 2.3.1
			dev_lukebemish_opensesame_opensesame-fabric: opensesame-fabric 0.6.0
				dev_lukebemish_opensesame_opensesame-core: opensesame-core 0.6.0
				opensesame_mixin: OpenSesame: Mixin Plugin 0.6.0
		revive: Revive 1.0.7
		rpgz: RPGZ 0.6.0
		ryoamiclights: RyoamicLights 0.2.9+mc1.21
		satin: Satin 2.0.0
		scorchful: Scorchful 0.9
		searchables: Searchables 1.0.1
		sereneseasons: SereneSeasons 10.0.0.2
		shouldersurfing: Shoulder Surfing Reloaded 4.2.0
		skeletonhorsespawn: Skeleton Horse Spawn 3.9
		skinlayers3d: 3d-Skin-Layers 1.6.6
		snuffles: Snuffles 1.2.0+1.21
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.5
		spark: spark 1.10.73
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		t_and_t: Towns and Towers 1.13.2
		tcdcommons: TCD Commons API 3.12.2+fabric-1.21
		thermoo: Thermoo 4.1.1
		utility_belt: Utility Belt 2.4.1+1.21
		vanillaconfig: Vanilla Config 1.2.11+1.21
		variantsandventures: Variants & Ventures 1.0.4
		villagerfix: Villager Trade Fix 1.0.4
		villagernames: Villager Names 8.0
		villagespawnpoint: Village Spawn Point 4.3
		visuality: Visuality 0.7.7+1.21
		visualworkbench: Visual Workbench 21.0.1
		wakes: Wakes 0.2.5+1.21
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
		waystones: Waystones 21.0.8
		wilderwild: Wilder Wild 2.4.6-mc1.21
			frozenlib: FrozenLib 1.8-mc1.21
		wover: WorldWeaver 21.0.9
			wover-biome: WorldWeaver - Biome API 21.0.9
			wover-block: WorldWeaver - Block and Item API 21.0.9
			wover-common: WorldWeaver - Common API 21.0.9
			wover-core: WorldWeaver - Core API 21.0.9
			wover-datagen: WorldWeaver - Datagen API 21.0.9
			wover-events: WorldWeaver - Events API 21.0.9
			wover-feature: WorldWeaver - Feature API 21.0.9
			wover-generator: WorldWeaver - World Generator API 21.0.9
			wover-item: WorldWeaver - Item API 21.0.9
			wover-math: WorldWeaver - Math API 21.0.9
			wover-preset: WorldWeaver - World Preset API 21.0.9
			wover-recipe: WorldWeaver - Recipe API 21.0.9
			wover-structure: WorldWeaver - Structure API 21.0.9
			wover-surface: WorldWeaver - Surface API 21.0.9
			wover-tag: WorldWeaver - Tag API 21.0.9
			wover-ui: WorldWeaver - UI API 21.0.9
			wunderlib: WunderLib 21.0.3
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
		zombiehorsespawn: Zombie Horse Spawn 5.0
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Teny_guy'/73, l='ServerLevel[New World]', x=-215.52, y=67.00, z=-197.15]]
	Active Data Packs: vanilla, fabric, accessories, additionalstructures, additionz, advancedcombat, advancednetherite, amethystequipment, amplified_nether (incompatible), animal_feeding_trough, armoroftheages (incompatible), backslot, backslotaddon, balm-fabric (incompatible), bclib, betterend, betternether, boneequipment, bosses_of_mass_destruction, cinderscapes-common, collective, creeperoverhaul, croptopia, dehydration, dragonloot, duckling, dynamiccrosshair-api, easyanvils (incompatible), easymagic (incompatible), elytratrims (incompatible), enchantment_lore, fabric-convention-tags-v2, fleshz, flowerymooblooms, friendsandfoes, frozenlib, geophilic, gobber2, greater_eye, guardvillagers, libertyvillagers, more_beautiful_torches (incompatible), more_bows_and_arrows (incompatible), netherdepthsupgrade, placeableblazerods, puffish_attributes, pugh_tools, repurposed_structures, revive, rpgz, scorchful, sereneseasons (incompatible), server_translations_api, snuffles, t_and_t, thermoo, utility_belt, variantsandventures, visualworkbench (incompatible), waystones (incompatible), wilderwild, wover-generator, wover-preset, wover-surface, wover-tag, resources/t_and_t_waystones_patch_resources/t_and_t_waystones_patch, skill_tree.zip (incompatible)
	Available Data Packs: accessories, additionalstructures, additionz, advancedcombat, advancednetherite, amethystequipment, amplified_nether (incompatible), animal_feeding_trough, armoroftheages (incompatible), backslot, backslotaddon, balm-fabric (incompatible), bclib, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, betternether, betternether:vanilla-hammers_extensions, betternether:vanillaexcavators_extensions, boneequipment, bosses_of_mass_destruction, bundle, cinderscapes-common, collective, creeperoverhaul, croptopia, dehydration, dragonloot, duckling, dynamiccrosshair-api, easyanvils (incompatible), easymagic (incompatible), elytratrims (incompatible), enchantment_lore, fabric, fabric-convention-tags-v2, fleshz, flowerymooblooms, friendsandfoes, frozenlib, geophilic, gobber2, greater_eye, guardvillagers, libertyvillagers, more_beautiful_torches (incompatible), more_bows_and_arrows (incompatible), netherdepthsupgrade, placeableblazerods, puffish_attributes, pugh_tools, repurposed_structures, resources/t_and_t_waystones_patch_resources/t_and_t_waystones_patch, revive, rpgz, scorchful, sereneseasons (incompatible), server_translations_api, skill_tree.zip (incompatible), snuffles, t_and_t, thermoo, trade_rebalance, utility_belt, vanilla, variantsandventures, visualworkbench (incompatible), waystones (incompatible), wilderwild, wover-generator, wover-preset, wover-surface, wover-tag
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -3787048898417994010
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.0-1.21
```

**Comment by Faboslav** [comment]
What do you mean? That is some issue related to `Verdant`, but triggered by `dehydration` mod, i double checked the code, and its the same as the vanilla one.

**Comment by TenKotowsky** [comment]
The game crashed when the Murk shot me with an arrorw so I thought it was the same issue 🤷‍♂️

**Comment by makumaku1974** [comment]
> What do you mean? That is some issue related to `Verdant`, but triggered by `dehydration` mod, i double checked the code, and its the same as the vanilla one.

is this globlox dehydration? I think forwarding this to him would be a good idea to see compatibilities.

**Comment by Faboslav** [comment]
I dont know, the mod id id just `dehydration`

**Comment by makumaku1974** [comment]
Will be closing this now.
